## The current file is auto-generated by script: generate_codec_ver.sh

import codec_app_def

var g_stCodecVersion* = OpenH264Version(
                          uMajor: 2,
                          uMinor: 1,
                          uRevision: 0 ,
                          uReserved: 2005
                        )

var g_strCodecVer*: string = "OpenH264 version:2.1.0.2005"

const
  OPENH264_MAJOR* = (2)
  OPENH264_MINOR* = (1)
  OPENH264_REVISION* = (0)
  OPENH264_RESERVED* = (2005)

